name: Deploy Node.js App using PM2 with Cache

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install PM2 globally
        run: npm install pm2 -g

      - name: Start app with PM2
        run: pm2 start index.js --name "my-node-app"

      - name: Save PM2 list
        run: pm2 save

      - name: Display PM2 logs
        run: pm2 logs
